add volume
symcon/SymconSpotify pull request #5
Opened 2020-10-29 11:09 UTC by Wolbolar

2020-11-04 08:48 UTC, DrNiels reviewed
Könntest du einmal erörtern, was du eigentlich alles geändert hast? Deine Anpassungen gehen ja deutlich über das Hinzufügen der Lautstärke hinaus. Wenn du mir erklären würdest, was hier alles passiert, dann kann ich das ganze auch viel besser reviewen.

Besten Dank!

2020-11-04 08:48 UTC, DrNiels commented on Spotify/form.json
> +                    "onClick": "SPO_Search_Configform($id, $SearchQuery, $SearchAlbums, $SearchArtists, $SearchPlaylists, $SearchTracks);"
Ich bin kein Freund des Unterstrichs im Funktionsnamen. Üblicherweise benennen wir die Funktionen in Camelcase, also bitte stattdessen SPO_SearchConfigForm

2020-11-04 08:48 UTC, DrNiels commented on Spotify/module.php
> +        }
Ist die Funktion nicht sinnlos? Die gibt doch einfach nur den Rückgabewert einer anderen Funktion zurück?

2020-11-05 22:39 UTC, Wolbolar commented
Es ist Lautstärke hinzugefügt worden, Position und Positionsabfrage, sowie eine seperate Methode zum Suchen hinzugefügt worden unabhänig von der Suche im Konfigform. Dmait man das auch z.B. im Webfront nutzten kann ohne gelich das Konfigform zu ändern.

 

Von: DrNiels <notifications@github.com> 
Gesendet: Mittwoch, 4. November 2020 09:48
An: symcon/SymconSpotify <SymconSpotify@noreply.github.com>
Cc: Fonzo <wolbolar@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [symcon/SymconSpotify] add volume (#5)

 

@DrNiels commented on this pull request.

Könntest du einmal erörtern, was du eigentlich alles geändert hast? Deine Anpassungen gehen ja deutlich über das Hinzufügen der Lautstärke hinaus. Wenn du mir erklären würdest, was hier alles passiert, dann kann ich das ganze auch viel besser reviewen.

Besten Dank!

  _____  

In Spotify/form.json <https://github.com/symcon/SymconSpotify/pull/5#discussion_r517177883> :

> @@ -67,7 +67,7 @@
 
                     "type": "Button",
 
                     "name": "Search",
 
                     "caption": "Start Search",
 
-                    "onClick": "SPO_Search($id, $SearchQuery, $SearchAlbums, $SearchArtists, $SearchPlaylists, $SearchTracks);"
 
+                    "onClick": "SPO_Search_Configform($id, $SearchQuery, $SearchAlbums, $SearchArtists, $SearchPlaylists, $SearchTracks);"
 

Ich bin kein Freund des Unterstrichs im Funktionsnamen. Üblicherweise benennen wir die Funktionen in Camelcase, also bitte stattdessen SPO_SearchConfigForm

 

Die Methode PO_SearchConfigForm dient außschließlich dazu diese von dem Konfigform aus aufzurufen und aktualisiert auch die Felder des Konfigform. Die Zusätzliche Methode Search ist zum eigentlichen Aufrufen per Skript. Der Unterschied ist nur das die Methode SPO_SearchConfigForm auch das Konfigform aktualisiert

  _____  

In Spotify/module.php <https://github.com/symcon/SymconSpotify/pull/5#discussion_r517180785> :

> +        public function CurrentPlayback()
 
+        {
 
+            return $currentPlay = $this->requestCurrentPlay();
 
+        }
 

Ist die Funktion nicht sinnlos? Die gibt doch einfach nur den Rückgabewert einer anderen Funktion zurück?

 

Nein die Methode ist nicht sinnlos sondern notwendig. Diese ruft eben nur zusätzlich eine private Methode auf die ansonsten nicht zugänglich ist. Dies braucht man ebenfalls um das in einem Skript oder dem Webfront nutzten zu können. 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/symcon/SymconSpotify/pull/5#pullrequestreview-523143789> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABDFES4P2TJTD7ZTI4ZJFMTSOEINNANCNFSM4TDSQ3IA> .  <https://github.com/notifications/beacon/ABDFES5UWASS6IU6T6HXDJLSOEINNA5CNFSM4TDSQ3IKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOD4XIU3I.gif>

2020-11-06 08:31 UTC, DrNiels commented
Bei der Funktion SPO_Search_Configform habe ich den Sinn schon verstanden, es ging mir lediglich um die Notation, sprich ich hätte lieber SPO_SearchConfigForm statt SPO_Search_Configform.

Dann passt die Funktion CurrentPlayback aber zu keiner deiner beschriebenen Änderungen, oder? Denn diese ist ja wieder für die Lautstärke, noch die Position, noch die Suche... Aber dann nehme ich das mal als weitere Änderung auf. Wenn du eine public-Funktion nutzt um eine private-Funktion nach außen zu leiten, dann solltest du eher die private-Funktion public machen anstatt eine neue Funktion zu definieren

2020-11-06 08:49 UTC, DrNiels requested changes
Insgesamt gefällt mir deine Implementation von UpdatePosition leider nicht. Du schickst hier (standardmäßig) jede Sekunde eine Anfrage raus, was meiner Meinung nach nicht notwendig ist um die Position aktuell zu halten.

Ich würde vorschlagen, dass du die Position im Rahmen der UpdateVariables-Funktion aktualisierst, wie du es implementiert hast. Sekündlich kannst du die Position dann lokal anpassen. Hier würde ich den Zeitstempel und die Position des letzten Aufrufs von UpdateVariables abspeichern und darauf basierend die neue Position bestimmen. Wenn ein Lied vorbei ist, kannst du gerne direkt UpdateVariables triggern. So hältst du die Anfragen meiner Meinung nach gering ohne an Mehrwert zu verlieren.

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +            $this->RegisterPropertyInteger('UpdateIntervalPosition', 1);
Man kann diese Eigenschaft gar nicht in der Form einstellen

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +            $this->RegisterVariableString('Remaining_Time', $this->Translate('Remaining Time'), '', 80);
Idents bitte als Camelcase und ohne _, also CurrentPosition und RemainingTime

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +            $this->RegisterVariableString('Search', $this->Translate('Search'), '~HTMLBox', 110);
Wofür sind die beiden Variablen denn da? Es wirkt so, als wenn die nicht zu deinen beschriebenen Änderungen passen.

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +        }
Die Funktionen passen alle nicht zu deinen beschriebenen Funktionen. Magst du die noch erörtern?

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +
Das scheint wieder eine Funktion zu sein, die nicht zu deinem beschriebenen Featureset passt. Abgesehen davon, ist die nicht redundant zu PlayURI?

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +                                            $newValue = '<iframe style="border: 0;" height="' . $imageObject['height'] . '" width = "' . $imageObject['width'] . '" src="' . $imageObject['url'] . '">'
Wozu ist diese Änderung?

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +                    $this->SendDebug('Volume', $current_volume, 0);
Warum setzt du die Volume in UpdatePosition?

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +                    $this->SendDebug('Current Position ms', $progress_ms, 0);
Da diese Funktion ja typischerweise jede Sekunde laufen sollte, flutest du hier ziemlich das Debug Log. Räume doch bitte noch einmal auf

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +                    $progress = $this->ConvertTimeInterval($progress_ms);
Da ConvertTimeInterval nur in dieser Funktion genutzt wird, definiere das gerne vor Ort als anonyme Funktion, siehe auch hier: https://www.php.net/manual/de/functions.anonymous.php

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +                    $remaining_time = $this->GetRemainingTime($progress_ms, $duration_ms);
Da diese Funktion nur hier genutzt wird, kannst du sie auch direkt hier anwenden und musst das nicht in eine Funktion auslagern

2020-11-06 08:49 UTC, DrNiels commented on Spotify/module.php
> +                    $position = $this->GetSongPosition($progress_ms, $duration_ms);
Diese Funktion wird ebenfalls nur dieses eine mal genutzt und kann daher hier reingezogen werden

2025-02-27 11:18 UTC, closed without merging

2025-02-27 11:18 UTC, TillBrede commented
Wir schließen der erstmal. Gerne mit den entsprechenden Änderungen wiedereröffnen.